# 工作流名称
name: Sync Images(from ghcr to aliyun)
# 怎样触发工作流
on:
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to aliyun
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://ghcr.io/wsc-studio/rust-red-runtime-base:full docker://registry.cn-hangzhou.aliyuncs.com/gshub/rust-red-runtime-base:full
        skopeo copy docker://ghcr.io/wsc-studio/rust-red-runtime-base:no-lo docker://registry.cn-hangzhou.aliyuncs.com/gshub/rust-red-runtime-base:no-lo
        skopeo copy docker://ghcr.io/wsc-studio/rust-red-runtime-base:no-ffmpeg docker://registry.cn-hangzhou.aliyuncs.com/gshub/rust-red-runtime-base:no-ffmpeg
        skopeo copy docker://ghcr.io/wsc-studio/rust-red-runtime-base:lite docker://registry.cn-hangzhou.aliyuncs.com/gshub/rust-red-runtime-base:lite
        skopeo copy docker://ghcr.io/wsc-studio/rust-red-builder-base:latest docker://registry.cn-hangzhou.aliyuncs.com/gshub/rust-red-builder-base:latest
        
